from flask import Flask, jsonify, render_template, redirect, url_for, request                                                                                                                                       
from textblob import Blobber                                                                                                                                                                                        
from textblob.sentiments import NaiveBayesAnalyzer                                                                                                                                                                  
from nltk.corpus import movie_reviews                                                                                                                                                                               
import re                                                                                                                                                                                                           
                                                                                                                                                                                                                    
app = Flask(__name__)                                                                                                                                                                                               
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
@app.route('/predict', methods=['POST'])                                                                                                                                                                            
def predict_a_tweet():                                                                                                                                                                                              
    tweet_content = request.json["submit"]                                                                                                                                                                          
    cleaned_tweet = clean_text(tweet_content)                                                                                                                                                                       
    positive_likelyhood = text_blob(cleaned_tweet).sentiment.p_pos                                                                                                                                                  
    print("Text: {0} Score: {1}".format(cleaned_tweet, positive_likelyhood))                                                                                                                                        
    if 0.45 <= positive_likelyhood <= 0.55:                                                                                                                                                                         
        return jsonify(sentiment="neutral", score=positive_likelyhood)                                                                                                                                              
    if positive_likelyhood > 0.60:                                                                                                                                                                                  
        return jsonify(sentiment="positive", score=positive_likelyhood)                                                                                                                                             
    else:                                                                                                                                                                                                           
        return jsonify(sentiment="negative", score=positive_likelyhood)                                                                                                                                             
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def clean_text(tweet_to_clean):                                                                                                                                                                                     
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet_to_clean).split())                                                                                                         
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
if __name__ == '__main__':                                                                                                                                                                                          
    text_blob = Blobber(analyzer=NaiveBayesAnalyzer())                                                                                                                                                              
    text_blob("Just there to build the model").sentiment                                                                                                                                                            
    app.run(host='0.0.0.0', debug=True)